name: Prettier Code Formatting Check

on:
  push:
  pull_request:

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Updated to use a newer Node version

      - name: Install dependencies using npm
        run: npm install
        working-directory: swt-ueberblick-app

      - name: Run Prettier
        run: npx prettier --check '**/*.{js,jsx,ts,tsx}' --ignore-path .prettierignore
        working-directory: swt-ueberblick-app
